import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Finance AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${mulish.className} antialiased dark`}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <div className="flex flex-col h-full overflow-hidden">{children}</div>
          <Toaster />
          <Analytics />
        </ClerkProvider>
      </body>
    </html>
  );
}
